### ISSUE TITLE
Display Doxygen in a tooltip

### ISSUE THREAD

**Issue by gvol** [Andersbakken/rtags#649] opened 2016-03-30 02:34 UTC
I would like the documentation support added in #116, to be available in a toolip much like `rtags-display-summary`.  Either the brief or prettified xml documentation.  I'm happy to help on the Emacs side.

I may have some time to add this in the future, but I suspect it will take me about 10 times as long to do as someone who is familiar with the code.

**Comment by wvdschel** [comment] 2016-04-06 11:49
Can this be considered a duplicate of #633 ?

**Comment by Andersbakken** [comment] 2016-04-06 16:39
I added the brief. Prettifying the xml will be a little more work but shouldn't be too hard if it's desirable.

**Closed by Andersbakken** 2016-04-06 16:39 UTC
