### ISSUE TITLE
Error messages for `company-rtags--make-candidate`

### ISSUE THREAD

**Issue by atilaneves** [Andersbakken/rtags#524] opened 2015-11-18 17:11 UTC
error in process filter: company-rtags--make-candidate: Args out of range: 0, 1
    error in process filter: Args out of range: 0, 1

Please let me know what else I can paste here.

**Comment by Andersbakken** [comment] 2015-11-18 17:33
Do you have a simple way to reproduce this?

If not, maybe you could do:

M-x toggle-debug-on-error

and paste the stack trace when it happens?

Anders

**Comment by cslux** [comment] 2015-11-18 17:34
I'm aware of this problem, which very rarely happens.

Nevertheless, can you please post the stack trace of the debugger, when this happens. `M-x
toggle-debug-on-error RET`


Christian

**Comment by cslux** [comment] 2015-11-18 20:05
I was able to reproduce it.

It always happens for me when `(nth 2 candidate)` is "CXXMethod" and `nth 0/1` is empty.

See image on how I was able to reproduce it. Note the cursor is at `s.`
![reproduce_company-rtags--make-candidate_bug](https://cloud.githubusercontent.com/assets/1712313/11252596/53490c8c-8e37-11e5-9c50-77168e9644f4.png)

Even after commenting out the code snippet rtags seems to stuck somehow, the syntax checker stills highlights the code. The output of rdm, however, should me that it has parsed the file.
![reproduce_company-rtags--make-candidate_comment_out_snippet](https://cloud.githubusercontent.com/assets/1712313/11252466/a5200304-8e36-11e5-8c7d-8e3f4d531c04.png)


Stack trace

``` emacs-lisp
Debugger entered--Lisp error: (args-out-of-range 0 1)
  put-text-property(0 1 meta-insert "" "")
  company-rtags--make-candidate(("" "" "CXXMethod") 46)
  rtags-company-diagnostics-hook()
  run-hooks(rtags-diagnostics-hook)
  rtags-parse-diagnostics()
  rtags-diagnostics-process-filter(#<process RTags Diagnostics> "(list 'completions (list \"src/Source.cpp:31:12:\" (list (list \"\" \"\" \"CXXMethod\") (list \"i\" \"int i\" \"FieldDecl\"))))\n")
```

@Andersbakken, can you give me some advice, how to further triage that problem? Thanks!

**Comment by Andersbakken** [comment] 2015-11-19 02:09
Can you check if this works now? I can't seem to reproduce it but that might be due to different clang versions or something like that.

**Comment by cslux** [comment] 2015-11-19 07:40
For me it is working now.

**Comment by atilaneves** [comment] 2015-11-19 09:33
Updated and still getting interrupted every few seconds. Debug on error gave me this:

    Debugger entered--Lisp error: (wrong-number-of-arguments length 2)
      length("asm" 0)
      company-rtags--valid-candidate(nil ("asm" "asm(string-literal)" "NotImplemented"))
      rtags-company-diagnostics-hook()
      run-hooks(rtags-diagnostics-hook)
      rtags-parse-diagnostics()
      rtags-diagnostics-process-filter(#<process RTags Diagnostics<1>> "(list 'checkstyle (cons \"/home/user/foo.cpp\" nil))))\n")

**Comment by Andersbakken** [comment] 2015-11-20 02:53
Ah. Sorry about that. Should be fixed now. I had the wrong fix in first.

Anders

**Closed** 2015-12-08 17:29 UTC
Labels: bug
