### ISSUE TITLE
CMake error building on Ubuntu

### ISSUE THREAD

**Issue by mwbuksas** [Andersbakken/rtags#507] opened 2015-11-04 16:45 UTC
When running ```cmake -DLIBCLANG_LIBRARIES="-L/usr/lib/llvm-3.6/lib"  ..```
```
CMake Error at src/CMakeLists.txt:152 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.
```
This is llvm 3.6 and CMake 3.0.2. 

Revisions: a9e2413 and 8907909 for src/rct.

Thanks.

**Comment by cslux** [comment] 2015-11-04 18:17
Hmm, I can't reproduce this with cmake 3.0.2. Did you run cmake in a clean build directory?

**Comment by mwbuksas** [comment] 2015-11-04 19:18
My default emacs appears to be broken, (I've been running a locally-built emacs24 by hand) so when cmake tries to get the version, it gets an error and fails the regex.

As a workaround I added -DEMACS_EXECUTABLE and all is well with CMake.

So, totally my bad. Thanks for checking though.

**Comment by cslux** [comment] 2015-11-04 19:27
> (I've been running a locally-built emacs24 by hand) so when cmake tries to get the version, it gets an error and fails the regex.

Ah ok, but still I would consider this as bug in the cmake file which needs to be fixed.

Could you please post the output of `emacs --version` "of the broken emacs", thanks.

**Comment by mwbuksas** [comment] 2015-11-04 19:49
It produces nothing on stdout, which I think is what you need. 

On stderr I get ```error while loading shared libraries: libgnutls.so.26: cannot open shared object file: No such file or directory```.

**Comment by cslux** [comment] 2015-11-04 19:53
Oh, seems like it is really broken :-) I will at least handle the case where emacs has been found but we where not able to get the version. 

Thanks, closing it now!

**Closed by cslux** 2015-11-04 19:53 UTC
