### ISSUE TITLE
Build failure on Ubuntu 14.04 with GCC 4.8

### ISSUE THREAD

**Issue by sdeber** [Andersbakken/rtags#1016] opened 2017-07-27 11:22 UTC
### Please mark appropriate
 - [X ] rtags (rdm/rc/rp)
 - Emacs Lisp
   - [ ] ac-rtags.el
   - [ ] company-rtags.el
   - [ ] helm-rtags.el
   - [ ] flycheck-rtags.el
   - [ ] ivy-rtags.el
   - [ ] rtags.el

### Problem description
I pulled the latest code from git on Ubuntu 14.04, then the compilation failed with the following logs:

In file included from /home/ak70/tmp/rtags/src/rct/rct/Flags.h:4:0,
                 from /home/ak70/tmp/rtags/src/rct/rct/Log.h:13,
                 from /home/ak70/tmp/rtags/src/rct/rct/Serializer.h:14,
                 from /home/ak70/tmp/rtags/src/Token.h:19,
                 from /home/ak70/tmp/rtags/src/ClangIndexer.h:20,
                 from /home/ak70/tmp/rtags/src/ClangIndexer.cpp:17:
/home/ak70/tmp/rtags/src/rct/rct/String.h: In constructor ‘String::String(const char*, const char*)’:
/home/ak70/tmp/rtags/src/rct/rct/String.h:38:5: warning: declaration of ‘end’ shadows a member of 'this' [-Wshadow]
     {
     ^
/home/ak70/tmp/rtags/src/rct/rct/String.h: In member function ‘size_t String::indexOf(char, size_t, String::CaseSensitivity) const’:
/home/ak70/tmp/rtags/src/rct/rct/String.h:106:21: warning: declaration of ‘data’ shadows a member of 'this' [-Wshadow]
         const char *data = mString.c_str();
                     ^
/home/ak70/tmp/rtags/src/rct/rct/String.h: In member function ‘String String::trimmed(const String&) const’:
/home/ak70/tmp/rtags/src/rct/rct/String.h:265:22: warning: declaration of ‘end’ shadows a member of 'this' [-Wshadow]
         const size_t end = mString.find_last_not_of(trim);
                      ^
/home/ak70/tmp/rtags/src/rct/rct/String.h: In member function ‘String::iterator String::erase(String::const_iterator, String::const_iterator)’:
/home/ak70/tmp/rtags/src/rct/rct/String.h:456:5: warning: declaration of ‘end’ shadows a member of 'this' [-Wshadow]
     {
     ^
/home/ak70/tmp/rtags/src/rct/rct/String.h:456:5: warning: declaration of ‘begin’ shadows a member of 'this' [-Wshadow]
/home/ak70/tmp/rtags/src/rct/rct/String.h:457:40: error: no matching function for call to ‘std::basic_string<char>::erase(String::const_iterator&, String::const_iterator&)’
         return mString.erase(begin, end);
                                        ^
/home/ak70/tmp/rtags/src/rct/rct/String.h:457:40: note: candidates are:
In file included from /usr/include/c++/4.8/string:52:0,
                 from /home/ak70/tmp/rtags/src/rct/rct/Serializer.h:10,
                 from /home/ak70/tmp/rtags/src/Token.h:19,
                 from /home/ak70/tmp/rtags/src/ClangIndexer.h:20,
                 from /home/ak70/tmp/rtags/src/ClangIndexer.cpp:17:
/usr/include/c++/4.8/bits/basic_string.h:1362:7: note: std::basic_string<_CharT, _Traits, _Alloc>& std::basic_string<_CharT, _Traits, _Alloc>::erase(std::basic_string<_CharT, _Traits, _Alloc>::size_type, std::basic_string<_CharT, _Traits, _Alloc>::size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]
       erase(size_type __pos = 0, size_type __n = npos)
       ^
/usr/include/c++/4.8/bits/basic_string.h:1362:7: note:   no known conversion for argument 1 from ‘String::const_iterator {aka __gnu_cxx::__normal_iterator<const char*, std::basic_string<char> >}’ to ‘std::basic_string<char>::size_type {aka long unsigned int}’
/usr/include/c++/4.8/bits/basic_string.h:1378:7: note: std::basic_string<_CharT, _Traits, _Alloc>::iterator std::basic_string<_CharT, _Traits, _Alloc>::erase(std::basic_string<_CharT, _Traits, _Alloc>::iterator) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::basic_string<_CharT, _Traits, _Alloc>::iterator = __gnu_cxx::__normal_iterator<char*, std::basic_string<char> >; typename _Alloc::rebind<_CharT>::other::pointer = char*]
       erase(iterator __position)
       ^
/usr/include/c++/4.8/bits/basic_string.h:1378:7: note:   candidate expects 1 argument, 2 provided
/usr/include/c++/4.8/bits/basic_string.h:1398:7: note: std::basic_string<_CharT, _Traits, _Alloc>::iterator std::basic_string<_CharT, _Traits, _Alloc>::erase(std::basic_string<_CharT, _Traits, _Alloc>::iterator, std::basic_string<_CharT, _Traits, _Alloc>::iterator) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::basic_string<_CharT, _Traits, _Alloc>::iterator = __gnu_cxx::__normal_iterator<char*, std::basic_string<char> >; typename _Alloc::rebind<_CharT>::other::pointer = char*]
       erase(iterator __first, iterator __last);
       ^
/usr/include/c++/4.8/bits/basic_string.h:1398:7: note:   no known conversion for argument 1 from ‘String::const_iterator {aka __gnu_cxx::__normal_iterator<const char*, std::basic_string<char> >}’ to ‘std::basic_string<char>::iterator {aka __gnu_cxx::__normal_iterator<char*, std::basic_string<char> >}’
In file included from /home/ak70/tmp/rtags/src/rct/rct/Flags.h:4:0,
                 from /home/ak70/tmp/rtags/src/rct/rct/Log.h:13,
                 from /home/ak70/tmp/rtags/src/rct/rct/Serializer.h:14,
                 from /home/ak70/tmp/rtags/src/Token.h:19,
                 from /home/ak70/tmp/rtags/src/ClangIndexer.h:20,
                 from /home/ak70/tmp/rtags/src/ClangIndexer.cpp:17:
/home/ak70/tmp/rtags/src/rct/rct/String.h: In member function ‘long long unsigned int String::toULongLong(bool*, size_t) const’:
/home/ak70/tmp/rtags/src/rct/rct/String.h:707:15: warning: declaration of ‘end’ shadows a member of 'this' [-Wshadow]
         char *end = 0;
               ^
/home/ak70/tmp/rtags/src/rct/rct/String.h: In member function ‘long long int String::toLongLong(bool*, size_t) const’:
/home/ak70/tmp/rtags/src/rct/rct/String.h:716:15: warning: declaration of ‘end’ shadows a member of 'this' [-Wshadow]
         char *end = 0;
               ^
/home/ak70/tmp/rtags/src/rct/rct/String.h: In member function ‘uint32_t String::toULong(bool*, size_t) const’:
/home/ak70/tmp/rtags/src/rct/rct/String.h:725:15: warning: declaration of ‘end’ shadows a member of 'this' [-Wshadow]
         char *end = 0;
               ^
/home/ak70/tmp/rtags/src/rct/rct/String.h: In member function ‘int32_t String::toLong(bool*, size_t) const’:
/home/ak70/tmp/rtags/src/rct/rct/String.h:734:15: warning: declaration of ‘end’ shadows a member of 'this' [-Wshadow]
         char *end = 0;
               ^
In file included from /home/ak70/tmp/rtags/src/Location.h:40:0,
                 from /home/ak70/tmp/rtags/src/Token.h:21,
                 from /home/ak70/tmp/rtags/src/ClangIndexer.h:20,
                 from /home/ak70/tmp/rtags/src/ClangIndexer.cpp:17:
/home/ak70/tmp/rtags/src/rct/rct/StackBuffer.h: In member function ‘void StackBuffer<Size, T>::resize(size_t)’:
/home/ak70/tmp/rtags/src/rct/rct/StackBuffer.h:23:5: warning: declaration of ‘size’ shadows a member of 'this' [-Wshadow]
     {
     ^
In file included from /home/ak70/tmp/rtags/src/Symbol.h:29:0,
                 from /home/ak70/tmp/rtags/src/RTags.h:32,
                 from /home/ak70/tmp/rtags/src/IndexerJob.h:21,
                 from /home/ak70/tmp/rtags/src/IndexDataMessage.h:20,
                 from /home/ak70/tmp/rtags/src/ClangIndexer.h:22,
                 from /home/ak70/tmp/rtags/src/ClangIndexer.cpp:17:
/home/ak70/tmp/rtags/src/rct/rct/Value.h: In member function ‘Value Value::convert(Value::Type, bool*) const’:
/home/ak70/tmp/rtags/src/rct/rct/Value.h:448:50: warning: declaration of ‘type’ shadows a member of 'this' [-Wshadow]
 inline Value Value::convert(Type type, bool *ok) const
                                                  ^
In file included from /home/ak70/tmp/rtags/src/RTags.h:39:0,
                 from /home/ak70/tmp/rtags/src/IndexerJob.h:21,
                 from /home/ak70/tmp/rtags/src/IndexDataMessage.h:20,
                 from /home/ak70/tmp/rtags/src/ClangIndexer.h:22,
                 from /home/ak70/tmp/rtags/src/ClangIndexer.cpp:17:
/home/ak70/tmp/rtags/src/IndexMessage.h: In member function ‘void IndexMessage::setProjectRoot(const Path&)’:
/home/ak70/tmp/rtags/src/IndexMessage.h:32:50: warning: declaration of ‘projectRoot’ shadows a member of 'this' [-Wshadow]
     void setProjectRoot(const Path &projectRoot) { mProjectRoot = projectRoot; }
                                                  ^
/home/ak70/tmp/rtags/src/IndexMessage.h: In member function ‘void IndexMessage::setEnvironment(const List<String>&)’:
/home/ak70/tmp/rtags/src/IndexMessage.h:35:58: warning: declaration of ‘environment’ shadows a member of 'this' [-Wshadow]
     void setEnvironment(const List<String> &environment) { mEnvironment = environment; }
                                                          ^
In file included from /home/ak70/tmp/rtags/src/ClangIndexer.h:22:0,
                 from /home/ak70/tmp/rtags/src/ClangIndexer.cpp:17:
/home/ak70/tmp/rtags/src/IndexDataMessage.h: In member function ‘void IndexDataMessage::setIndexerJobFlags(Flags<IndexerJob::Flag>)’:
/home/ak70/tmp/rtags/src/IndexDataMessage.h:82:60: warning: declaration of ‘flags’ shadows a member of 'this' [-Wshadow]
     void setIndexerJobFlags(Flags<IndexerJob::Flag> flags) { mIndexerJobFlags = flags; }
                                                            ^
In file included from /home/ak70/tmp/rtags/src/rct/rct/SocketClient.h:6:0,
                 from /home/ak70/tmp/rtags/src/rct/rct/SocketServer.h:10,
                 from /home/ak70/tmp/rtags/src/Server.h:23,
                 from /home/ak70/tmp/rtags/src/ClangIndexer.h:27,
                 from /home/ak70/tmp/rtags/src/ClangIndexer.cpp:17:
/home/ak70/tmp/rtags/src/rct/rct/Buffer.h: In member function ‘size_t Buffers::read(void*, size_t)’:
/home/ak70/tmp/rtags/src/rct/rct/Buffer.h:118:5: warning: declaration of ‘size’ shadows a member of 'this' [-Wshadow]
     {
     ^
/home/ak70/tmp/rtags/src/rct/rct/Buffer.h:123:16: warning: declaration of ‘read’ shadows a member of 'this' [-Wshadow]
         size_t read = 0, remaining = size;
                ^
In file included from /home/ak70/tmp/rtags/src/rct/rct/SocketServer.h:10:0,
                 from /home/ak70/tmp/rtags/src/Server.h:23,
                 from /home/ak70/tmp/rtags/src/ClangIndexer.h:27,
                 from /home/ak70/tmp/rtags/src/ClangIndexer.cpp:17:
/home/ak70/tmp/rtags/src/rct/rct/SocketClient.h: In member function ‘String SocketClient::peerString() const’:
/home/ak70/tmp/rtags/src/rct/rct/SocketClient.h:64:18: warning: declaration of ‘port’ shadows a member of 'this' [-Wshadow]
         uint16_t port;
                  ^
/home/ak70/tmp/rtags/src/rct/rct/SocketClient.h: In member function ‘String SocketClient::sockString() const’:
/home/ak70/tmp/rtags/src/rct/rct/SocketClient.h:74:18: warning: declaration of ‘port’ shadows a member of 'this' [-Wshadow]
         uint16_t port;
                  ^
/home/ak70/tmp/rtags/src/rct/rct/SocketClient.h: In member function ‘bool SocketClient::writeTo(const String&, uint16_t, const String&)’:
/home/ak70/tmp/rtags/src/rct/rct/SocketClient.h:85:5: warning: declaration of ‘port’ shadows a member of 'this' [-Wshadow]
     {
     ^
In file included from /home/ak70/tmp/rtags/src/ClangIndexer.cpp:17:0:
/home/ak70/tmp/rtags/src/ClangIndexer.h: In member function ‘std::shared_ptr<ClangIndexer::Unit>& ClangIndexer::unit(uint32_t)’:
/home/ak70/tmp/rtags/src/ClangIndexer.h:145:32: warning: declaration of ‘unit’ shadows a member of 'this' [-Wshadow]
         std::shared_ptr<Unit> &unit = mUnits[fileId];
                                ^
In file included from /home/ak70/tmp/rtags/src/QueryMessage.h:21:0,
                 from /home/ak70/tmp/rtags/src/ClangIndexer.cpp:26:
/home/ak70/tmp/rtags/src/Match.h: In constructor ‘Match::Match(const String&, Flags<Match::Flag>)’:
/home/ak70/tmp/rtags/src/Match.h:110:57: warning: declaration of ‘pattern’ shadows a member of 'this' [-Wshadow]
 inline Match::Match(const String &pattern, Flags<Flag> f)
                                                         ^
In file included from /home/ak70/tmp/rtags/src/ClangIndexer.cpp:26:0:
/home/ak70/tmp/rtags/src/QueryMessage.h: In member function ‘void QueryMessage::setKindFilters(const QueryMessage::KindFilters&)’:
/home/ak70/tmp/rtags/src/QueryMessage.h:182:57: warning: declaration of ‘kindFilters’ shadows a member of 'this' [-Wshadow]
     void setKindFilters(const KindFilters &kindFilters) { mKindFilters = kindFilters; }
                                                         ^
/home/ak70/tmp/rtags/src/QueryMessage.h: In member function ‘void QueryMessage::setUnsavedFiles(const UnsavedFiles&)’:
/home/ak70/tmp/rtags/src/QueryMessage.h:185:60: warning: declaration of ‘unsavedFiles’ shadows a member of 'this' [-Wshadow]
     void setUnsavedFiles(const UnsavedFiles &unsavedFiles) { mUnsavedFiles = unsavedFiles; }
                                                            ^
/home/ak70/tmp/rtags/src/QueryMessage.h: In member function ‘void QueryMessage::setQuery(String&&)’:
/home/ak70/tmp/rtags/src/QueryMessage.h:193:35: warning: declaration of ‘query’ shadows a member of 'this' [-Wshadow]
     void setQuery(String &&query) { mQuery = std::move(query); }
                                   ^
/home/ak70/tmp/rtags/src/QueryMessage.h: In member function ‘void QueryMessage::setRangeFilter(int, int)’:
/home/ak70/tmp/rtags/src/QueryMessage.h:203:5: warning: declaration of ‘max’ shadows a member of 'this' [-Wshadow]
     {
     ^
/home/ak70/tmp/rtags/src/QueryMessage.h: In member function ‘void QueryMessage::setMax(int)’:
/home/ak70/tmp/rtags/src/QueryMessage.h:212:26: warning: declaration of ‘max’ shadows a member of 'this' [-Wshadow]
     void setMax(int max) { mMax = max; }
                          ^
/home/ak70/tmp/rtags/src/QueryMessage.h: In member function ‘void QueryMessage::setFlags(Flags<QueryMessage::Flag>)’:
/home/ak70/tmp/rtags/src/QueryMessage.h:216:5: warning: declaration of ‘flags’ shadows a member of 'this' [-Wshadow]
     {
     ^
/home/ak70/tmp/rtags/src/QueryMessage.h: In member function ‘void QueryMessage::setCurrentFile(const Path&)’:
/home/ak70/tmp/rtags/src/QueryMessage.h:240:50: warning: declaration of ‘currentFile’ shadows a member of 'this' [-Wshadow]
     void setCurrentFile(const Path &currentFile) { mCurrentFile = currentFile; }
                                                  ^
In file included from /home/ak70/tmp/rtags/src/rct/rct/Connection.h:4:0,
                 from /home/ak70/tmp/rtags/src/ClangIndexer.cpp:28:
/home/ak70/tmp/rtags/src/rct/rct/FinishMessage.h: In constructor ‘FinishMessage::FinishMessage(int)’:
/home/ak70/tmp/rtags/src/rct/rct/FinishMessage.h:12:9: warning: declaration of ‘status’ shadows a member of 'this' [-Wshadow]
         : Message(MessageId), mStatus(status)
         ^
In file included from /home/ak70/tmp/rtags/src/rct/rct/Connection.h:6:0,
                 from /home/ak70/tmp/rtags/src/ClangIndexer.cpp:28:
/home/ak70/tmp/rtags/src/rct/rct/ResponseMessage.h: In constructor ‘ResponseMessage::ResponseMessage(const String&, ResponseMessage::Type)’:
/home/ak70/tmp/rtags/src/rct/rct/ResponseMessage.h:14:9: warning: declaration of ‘type’ shadows a member of 'this' [-Wshadow]
         : Message(MessageId), mData(data), mType(type)
         ^
/home/ak70/tmp/rtags/src/rct/rct/ResponseMessage.h:14:9: warning: declaration of ‘data’ shadows a member of 'this' [-Wshadow]
/home/ak70/tmp/rtags/src/rct/rct/ResponseMessage.h: In constructor ‘ResponseMessage::ResponseMessage(const List<String>&, ResponseMessage::Type)’:
/home/ak70/tmp/rtags/src/rct/rct/ResponseMessage.h:20:9: warning: declaration of ‘type’ shadows a member of 'this' [-Wshadow]
         : Message(MessageId), mData(String::join(data, "\n")), mType(type)
         ^
/home/ak70/tmp/rtags/src/rct/rct/ResponseMessage.h:20:9: warning: declaration of ‘data’ shadows a member of 'this' [-Wshadow]
/home/ak70/tmp/rtags/src/rct/rct/ResponseMessage.h: In member function ‘void ResponseMessage::setData(const String&)’:
/home/ak70/tmp/rtags/src/rct/rct/ResponseMessage.h:29:38: warning: declaration of ‘data’ shadows a member of 'this' [-Wshadow]
     void setData(const String &data) { mData = data; }
                                      ^
In file included from /home/ak70/tmp/rtags/src/ClangIndexer.cpp:28:0:
/home/ak70/tmp/rtags/src/rct/rct/Connection.h: In member function ‘void Connection::setVersion(int)’:
/home/ak70/tmp/rtags/src/rct/rct/Connection.h:31:34: warning: declaration of ‘version’ shadows a member of 'this' [-Wshadow]
     void setVersion(int version) { mVersion = version; }
                                  ^
In file included from /home/ak70/tmp/rtags/src/ClangIndexer.cpp:28:0:
/home/ak70/tmp/rtags/src/rct/rct/Connection.h: In member function ‘void Connection::onSocketError(const SharedPtr&, SocketClient::Error)’:
/home/ak70/tmp/rtags/src/rct/rct/Connection.h:91:5: warning: declaration of ‘error’ shadows a member of 'this' [-Wshadow]
     {
     ^
In file included from /home/ak70/tmp/rtags/src/ClangIndexer.cpp:33:0:
/home/ak70/tmp/rtags/src/VisitFileMessage.h: In constructor ‘VisitFileMessage::VisitFileMessage(const Path&, const Path&, uint32_t)’:
/home/ak70/tmp/rtags/src/VisitFileMessage.h:27:9: warning: declaration of ‘sourceFileId’ shadows a member of 'this' [-Wshadow]
         : RTagsMessage(MessageId), mFile(file), mProject(project), mSourceFileId(sourceFileId)
         ^
/home/ak70/tmp/rtags/src/VisitFileMessage.h:27:9: warning: declaration of ‘project’ shadows a member of 'this' [-Wshadow]
/home/ak70/tmp/rtags/src/VisitFileMessage.h:27:9: warning: declaration of ‘file’ shadows a member of 'this' [-Wshadow]
In file included from /home/ak70/tmp/rtags/src/ClangIndexer.cpp:34:0:
/home/ak70/tmp/rtags/src/VisitFileResponseMessage.h: In constructor ‘VisitFileResponseMessage::VisitFileResponseMessage(uint32_t, bool)’:
/home/ak70/tmp/rtags/src/VisitFileResponseMessage.h:27:9: warning: declaration of ‘visit’ shadows a member of 'this' [-Wshadow]
         : RTagsMessage(MessageId), mFileId(fileId), mVisit(visit)
         ^
/home/ak70/tmp/rtags/src/VisitFileResponseMessage.h:27:9: warning: declaration of ‘fileId’ shadows a member of 'this' [-Wshadow]
/home/ak70/tmp/rtags/src/ClangIndexer.cpp: In member function ‘bool ClangIndexer::exec(const String&)’:
/home/ak70/tmp/rtags/src/ClangIndexer.cpp:239:22: warning: declaration of ‘unit’ shadows a member of 'this' [-Wshadow]
     for (const auto &unit : mUnits) {
                      ^
/home/ak70/tmp/rtags/src/ClangIndexer.cpp: In member function ‘bool ClangIndexer::parse()’:
/home/ak70/tmp/rtags/src/ClangIndexer.cpp:1887:14: warning: declaration of ‘unit’ shadows a member of 'this' [-Wshadow]
         auto unit = RTags::TranslationUnit::create(mSourceFile, args, &unsavedFiles[0], unsavedIndex, flags);
              ^
/home/ak70/tmp/rtags/src/ClangIndexer.cpp: In member function ‘bool ClangIndexer::visit()’:
/home/ak70/tmp/rtags/src/ClangIndexer.cpp:2358:21: warning: declaration of ‘unit’ shadows a member of 'this' [-Wshadow]
         const auto &unit = mTranslationUnits.at(mCurrentTranslationUnit);
                     ^
In file included from /home/ak70/tmp/rtags/src/rct/rct/Hash.h:7:0,
                 from /home/ak70/tmp/rtags/src/rct/rct/Serializer.h:12,
                 from /home/ak70/tmp/rtags/src/Token.h:19,
                 from /home/ak70/tmp/rtags/src/ClangIndexer.h:20,
                 from /home/ak70/tmp/rtags/src/ClangIndexer.cpp:17:
/home/ak70/tmp/rtags/src/rct/rct/List.h: In instantiation of ‘size_t List<T>::indexOf(const T&) const [with T = String; size_t = long unsigned int]’:
/home/ak70/tmp/rtags/src/ClangIndexer.cpp:1654:80:   required from here
/home/ak70/tmp/rtags/src/rct/rct/List.h:116:61: warning: declaration of ‘end’ shadows a member of 'this' [-Wshadow]
         const typename Base::const_iterator end = Base::end();
                                                             ^
In file included from /home/ak70/tmp/rtags/src/rct/rct/Log.h:16:0,
                 from /home/ak70/tmp/rtags/src/rct/rct/Serializer.h:14,
                 from /home/ak70/tmp/rtags/src/Token.h:19,
                 from /home/ak70/tmp/rtags/src/ClangIndexer.h:20,
                 from /home/ak70/tmp/rtags/src/ClangIndexer.cpp:17:
/home/ak70/tmp/rtags/src/rct/rct/Map.h: In instantiation of ‘Map<Key, Value, Compare>& Map<Key, Value, Compare>::unite(const Map<Key, Value, Compare>&, size_t*) [with Key = Location; Value = Map<String, short unsigned int>; Compare = std::less<Location>; size_t = long unsigned int]’:
/home/ak70/tmp/rtags/src/ClangIndexer.cpp:2054:51:   required from here
/home/ak70/tmp/rtags/src/rct/rct/Map.h:129:31: warning: declaration of ‘count’ shadows a member of 'this' [-Wshadow]
     Map<Key, Value, Compare> &unite(const Map<Key, Value, Compare> &other, size_t *count = 0)
                               ^
/home/ak70/tmp/rtags/src/rct/rct/Map.h:132:36: warning: declaration of ‘end’ shadows a member of 'this' [-Wshadow]
         const auto end = other.end();
                                    ^
make[2]: *** [src/CMakeFiles/rtags.dir/ClangIndexer.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/rtags.dir/all] Error 2
make: *** [all] Error 2

#### Expected behavior
Compilation Successful

#### Actual behavior
Compilation failed

### Environment
- Your operating system:
Ubuntu 14.04 64bit
- LLVM/Clang version:
3.9
### Feature request

Describe the feature we should add to **RTags**.

**Comment by papadokolos** [comment] 2017-07-31 17:44
This seems to be a duplicate of #1015, and it no longer occurs on `master` branch (only in `v2.11`).
So I guess that the problem was fixed (on `master`) and that `v2.11` is currently broken.

**Comment by clearmisp** [comment] 2017-08-01 09:49
I have the same problem on openSUSE Leap 42.3.

**Comment by Andersbakken** [comment] 2017-08-03 04:10
@Mikael

It should work now. Can you check with HEAD?

Anders

**Closed** 2018-06-07 15:57 UTC
