### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by duud** [Andersbakken/rtags#423] opened 2015-09-07 03:59 UTC
Thx for this Andersbakken, rtags is very usefull.
I tried this for the firs time, so I have some questions.

After saving a file, preprocessor branches which aren't used are highlighted. This is very usefull for exploring new projects. I'm not sure how it workd, but is it possible to highlight preprocessor branches on every new opened file belongig to the project? Now I have to modify the file + save it to get the highlighting.

Company-rtags doesn't autocomplete after typing '...->' I have to type one charakter more e.g. '...->a' to get the completion-popup, this is somewhat inconvenient.

Is it possible to configure rtags to save it's database inside the project-root? - such that I can move the project to another directory or delete it without caring about the ~/.rtags directory

**Comment by duud** [comment] 2015-09-08 09:22
Motivation for highlighting of preprocessor branches....
The linux kerne-tree contains tons of ifdefs for different architectures and kernel-configurations. Searching for tags e.g. with gnu-global is very inconvenient because there maybe tons of definitions for a symbol. So you really need compilation flags to find the right definition and thats why rtags is so handy here. 
Since there are so many ifdefs in the code it's really helpful to see which branches are taken. Rtags highlights skipped preprocessor brances but I'm not sure how this is supposed to work. To get this working I execute `rtags-reparse-file` but if I do this in a header file 1200+ files, which are unmodified, get dirtied and reparsed. So is there a way to highlight warnings/errors + skipped preprocessor lines without the need for reparsing of 1200+ files so that it can be enabled for every file by default, maybe I'm missing something.

**Comment by cslux** [comment] 2015-09-08 10:28
Hey @Anders,

that is something which bothers me too. The highlighting always works on the
first opened file but fails on all others. The only thing which helps is to
reparse the file, but takes usually a long time because as @duud stated several
100 files need to be reparsed too.

Thanks,
Christian

**Comment by Andersbakken** [comment] 2015-09-09 05:57
This absolutely seems like a good idea. I implemented it and it seems to
work. (had to change the db version for it though).

Let me know how it works out.

Anders

**Comment by Andersbakken** [comment] 2015-09-09 06:01
I think the first issue should be fixed now.

I think you can get the company auto-completion thing to work the way you
want by doing this:
(setq company-minimum-prefix-length 0)

I don't actually use company-mode myself so I'm not 100% sure but it seemed
to work for me. Note that there is a delay simply because clang takes some
time to generate the completions.

I'm afraid it's not possible to have rtags store the data elsewhere at this
point. You can clean out certain projects using rc -W though

E.g.

rc -W /path/to/project

or if you want to clean out everything:

rc -C

Anders

**Comment by duud** [comment] 2015-09-09 11:48
Thx, this is very useful and work well so far for me.

One think that confuses me is the behavior on .h files. If I open a .h
file no diagnostics are shown for it, which does make sense since it's
not a .c file and there are no compilation flags for it, but if I
executed rtags-reparse-file on it I'm getting highlightings for
preprocessor branches on it. Once I've executed rtags-reparse-file on a
.h file the same highlightings are show every time I open this file again.

**Comment by Andersbakken** [comment] 2015-09-11 06:15
Have you updated to the latest version? I can't actually reproduce this. I
get diagnostics for headers the first time I open them (assuming they have
been indexed before).

Anders

**Comment by duud** [comment] 2015-09-11 09:48
Thx, latest version is working as expected.

**Comment by Andersbakken** [comment] 2015-09-11 15:13
Awesome. Let me know if you into other issues.

Anders

**Closed** 2015-10-08 01:04 UTC
