### ISSUE TITLE
rdm hangs in cygwin 

### ISSUE THREAD

**Issue by zijianyue** [Andersbakken/rtags#389] opened 2015-08-01 08:23 UTC
I've successfully compiled rtags in cygwin using below command

zijianyue@zijianyue-PC /cygdrive/e/rtags-master
$ cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=1
-- llvm-config found at: /usr/bin/llvm-config.exe
-- Using Clang 3.5.2 from /usr/lib with LIBS /usr/lib/libclang.dll.a and CXXFLAGS -I/usr/include  -DNDEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -O3  -g -std=gnu++11 -fvisibility-inlines-hidden -fno-exceptions -Woverloaded-virtual -Wcast-qual
-- Using win32 FileSystemWatcher
CMake Warning (dev) at cmake/EnsureLibraries.cmake:7 (GET_TARGET_PROPERTY):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "rct".  Use the target
  name directly with add_custom_command, or use the generator expression
  $<TARGET_FILE>, as appropriate.

Call Stack (most recent call first):
  src/CMakeLists.txt:136 (EnsureLibraries)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/EnsureLibraries.cmake:11 (GET_TARGET_PROPERTY):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "rdm".  Use the target
  name directly with add_custom_command, or use the generator expression
  $<TARGET_FILE>, as appropriate.

Call Stack (most recent call first):
  src/CMakeLists.txt:136 (EnsureLibraries)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /cygdrive/e/rtags-master

$ make

Then put all files from rtags-master/bin to cygwin/bin.
But rdm hangs like below:

zijianyue@zijianyue-PC /cygdrive/e/rtags-master
$ rdm --verbose
listening /home/zijianyue/.rdm
Running with 4 jobs, using args: -ferror-limit=0 -Wall -fspell-checking -Wno-unknown-warning-option
Includepaths: -isystem /usr/lib/clang/3.5.2/include/

**Comment by cslux** [comment] 2015-08-01 13:25
@zijianyue 

> But rdm hangs like below:

What do you mean by hanging?

`rdm` (server) is supposed to run in the "background", waiting for instruction from `rc` (client).

Example:
``` sh
rdm &
rc -J path/to/compile_commands.json 
```

Christian

**Comment by Andersbakken** [comment] 2015-08-01 23:58
Yeah. rdm runs as a daemon. (We should probably make an option to have it
detach from the terminal actually).

Anders

**Comment by zijianyue** [comment] 2015-08-02 05:26
Thanks for your instant reply .Now I encounter a problem that rdm can't stop when parsing.
I started one cygwin shell and run rdm --verbose &, then I started another cygwin shell and go to e:/rtags-master dir, and run rc -J , it returned OK like below:

zijianyue@zijianyue-PC /cygdrive/e/rtags-master
$ rc -J
[Server] Compilation database loaded

However, the rdm shell couldn't stop , it seemed some error happened when parsing the database.I got some information from it ,but don't know how to resolve it, please help.

/cygdrive/e/rtags-master/src/rct/rct/Connection.cpp
/usr/lib/gcc/i686-pc-cygwin/4.9.3/include/c++/mutex:707:10: error: thread-local storage is not supported for the current target

Can't decide which of these symbols are right for me MemberRefExpr r /cygdrive/e/rtags-master/src/rct/rct/Map.h:42:69 List<CXCursor>(CXXMethod c find(const key_type &) find def c:@N@std@CT>4#T#T#T#T@map@F@find#&1t0.0# /usr/lib/gcc/i686-pc-cygwin/4.9.3/include/c++/bits/stl_map.h:859:7, CXXMethod c find(const key_type &) find def c:@N@std@CT>4#T#T#T#T@map@F@find#&1t0.0#1 /usr/lib/gcc/i686-pc-cygwin/4.9.3/include/c++/bits/stl_map.h:874:7) Need to parse types

**Comment by zijianyue** [comment] 2015-08-02 05:33
By the way ,I guess the -isystem of rdm is not correct,
Includepaths: -isystem /usr/lib/clang/3.5.2/include/
but it actually is below value in cygwin:
Includepaths: -isystem /usr/lib/clang/i686-pc-cygwin/3.5.2/include/

**Comment by cslux** [comment] 2015-08-02 08:04
I think it finds the wrong system include headers.

Try this
rdm --verbose -isystem  /usr/lib/clang/i686-pc-cygwin/3.5.2/include/

**Comment by zijianyue** [comment] 2015-08-02 08:59
I tried rdm --verbose -isystem  /usr/lib/clang/i686-pc-cygwin/3.5.2/include/ ,but the rdm still can't stop, errors above are still exist.

**Comment by cslux** [comment] 2015-10-08 22:50
Today I tested it in Cygwin too, unfortunately, thread-local is not supported, also known as Thread Local Storage (TLS), right now I have no idea how to workaround this issue.

See e.g.
https://cygwin.com/ml/cygwin/2012-09/msg00069.html
http://pp.info.uni-karlsruhe.de/~firm/bugs/view.php?id=41

Same problem as in issue https://github.com/Andersbakken/rtags/issues/215#issuecomment-76720226

**Comment by Andersbakken** [comment] 2015-10-09 00:40
I guess we could use pthread for all of this.

Will look into it.

Anders

**Comment by Andersbakken** [comment] 2015-10-09 03:05
I just realized the problem isn't in rtags itself.

Maybe you could try to run rtags like this:

rdm -Dthread_local

Let me know how that works.

Anders

**Comment by cslux** [comment] 2015-10-09 09:38
> I just realized the problem isn't in rtags itself.

Absolutely, it has nothing to do with rtags. It's a problem with clang not supporting TLS on this platform, see http://comments.gmane.org/gmane.os.cygwin/148560

So I guess there is not really something we can do right now about this, but should probably work with a newer version of clang (maybe 3.8 at least it has a flag to select the TLS to use http://clang.llvm.org/docs/UsersManual.html#cmdoption-ftls-model).


I also tried to compile rtags with clang, and it fails for the same reason way the indexing doesn't work.
``` bash
/usr/lib/gcc/x86_64-pc-cygwin/4.9.3/include/c++/mutex:707:10: error: thread-local storage is not supported for the current target
  extern __thread void* __once_callable;
         ^
/usr/lib/gcc/x86_64-pc-cygwin/4.9.3/include/c++/mutex:708:10: error: thread-local storage is not supported for the current target
  extern __thread void (*__once_call)();
``` 

Further I had to set `HAS_CXX11` to true in [rct.cmake](https://github.com/Andersbakken/rct/blob/master/rct.cmake#L188), otherwise the test program would fail. This also failed on my fedora workstation. That's probably just some misconfiguration in the cmake file.

``` bash

 -- Using Clang 3.5.2 from /usr/lib with LIBS /usr/lib/libclang.dll.a and CXXFLAGS -I/usr/include  -DNDEBUG -D_GNU_SOURCE
 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -O3  -g -std=gnu++11 -fvisibility-inlines-hidden
 -fno-exceptions -Woverloaded-virtual -Wcast-qual

 -- Using win32 FileSystemWatcher

 CMake Warning (dev) at cmake/EnsureLibraries.cmake:7 (GET_TARGET_PROPERTY):
   Policy CMP0026 is not set: Disallow use of the LOCATION target property.
   Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
   command to set the policy and suppress this warning.

   The LOCATION property should not be read from target "rct".  Use the target
   name directly with add_custom_command, or use the generator expression
   $<TARGET_FILE>, as appropriate.

 Call Stack (most recent call first):
   src/CMakeLists.txt:137 (EnsureLibraries)
 This warning is for project developers.  Use -Wno-dev to suppress it.


 CMake Warning (dev) at cmake/EnsureLibraries.cmake:11 (GET_TARGET_PROPERTY):
   Policy CMP0026 is not set: Disallow use of the LOCATION target property.
   Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
   command to set the policy and suppress this warning.

   The LOCATION property should not be read from target "rdm".  Use the target
   name directly with add_custom_command, or use the generator expression
   $<TARGET_FILE>, as appropriate.

 Call Stack (most recent call first):
   src/CMakeLists.txt:137 (EnsureLibraries)
 This warning is for project developers.  Use -Wno-dev to suppress it.


 Copying files from /home/cschwarzgruber/Develop/rtags/bin to /home/cschwarzgruber/Develop/rtags/build/bin

 You have changed variables that require your cache to be deleted.
 Configure will be re-run and you may have to reset some variables.
 The following variables have changed:
 CMAKE_C_COMPILER= /usr/bin/clang.exe
 CMAKE_CXX_COMPILER= /usr/bin/clang++
 CMAKE_C_COMPILER= /usr/bin/clang.exe
 CMAKE_CXX_COMPILER= /usr/bin/clang++


 -- Using Clang 3.5.2 from /usr/lib with LIBS /usr/lib/libclang.dll.a and CXXFLAGS -I/usr/include  -DNDEBUG -D_GNU_SOURCE
 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -O3  -g -std=gnu++11 -fvisibility-inlines-hidden
 -fno-exceptions -Woverloaded-virtual -Wcast-qual

 -- Using win32 FileSystemWatcher

 CMake Error at src/rct/rct.cmake:207 (message):
   C++11 support not detected.  rct requires a modern compiler, GCC >= 4.8 or
   Clang >= 3.2 should suffice
 Call Stack (most recent call first):
   src/rct/CMakeLists.txt:2 (include)
```
 
Here is some compile output of the rtags compilation, using gcc. I'll post it too as it had some warnings in it, which need probably be investigated.

``` bash
[  1%] Building CXX object src/CMakeFiles/rtags.dir/IndexMessage.cpp.o
[  2%] Building CXX object src/CMakeFiles/rtags.dir/Location.cpp.o
[  4%] Building CXX object src/CMakeFiles/rtags.dir/Symbol.cpp.o
[  5%] Building CXX object src/rct/CMakeFiles/rct.dir/rct/AES256CBC.cpp.o
[  7%] Building CXX object src/rct/CMakeFiles/rct.dir/rct/Buffer.cpp.o
[  8%] Building CXX object src/rct/CMakeFiles/rct.dir/rct/Config.cpp.o
[ 10%] Building CXX object src/CMakeFiles/rtags.dir/QueryMessage.cpp.o
[ 11%] Building CXX object src/rct/CMakeFiles/rct.dir/rct/Connection.cpp.o
[ 12%] Building CXX object src/rct/CMakeFiles/rct.dir/rct/CpuUsage.cpp.o
[ 14%] Building CXX object src/CMakeFiles/rtags.dir/RTags.cpp.o
/home/cschwarzgruber/Develop/rtags/src/rct/rct/CpuUsage.cpp:106:2: Warnung: #warning "CpuUsage not implemented for this platform" [-Wcpp]
 #warning "CpuUsage not implemented for this platform"
  ^
[ 15%] Building CXX object src/rct/CMakeFiles/rct.dir/rct/Date.cpp.o
[ 17%] Building CXX object src/rct/CMakeFiles/rct.dir/rct/EventLoop.cpp.o
/home/cschwarzgruber/Develop/rtags/src/rct/rct/EventLoop.cpp:706:2: Warnung: #warning this is not optimal [-Wcpp]
 #warning this is not optimal
  ^
[ 18%] Building CXX object src/rct/CMakeFiles/rct.dir/rct/FileSystemWatcher.cpp.o
[ 20%] Building CXX object src/rct/CMakeFiles/rct.dir/rct/Log.cpp.o
[ 47%] Building CXX object src/rct/CMakeFiles/rct.dir/rct/Value.cpp.o
[ 48%] Building C object src/rct/CMakeFiles/rct.dir/cJSON/cJSON.c.o
/home/cschwarzgruber/Develop/rtags/src/rct/cJSON/cJSON.c: In Funktion »cJSON_strcasecmp«:
/home/cschwarzgruber/Develop/rtags/src/rct/cJSON/cJSON.c:42:5: Warnung: Feldindex hat Typ »char« [-Wchar-subscripts]
     for(; tolower(*s1) == tolower(*s2); ++s1, ++s2) if(*s1 == 0) return 0;
     ^
/home/cschwarzgruber/Develop/rtags/src/rct/cJSON/cJSON.c:42:5: Warnung: Feldindex hat Typ »char« [-Wchar-subscripts]
[ 50%] Building CXX object src/rct/CMakeFiles/rct.dir/rct/FileSystemWatcher_win32.cpp.o
[ 51%] Linking CXX static library librct.a
[ 51%] Built target rct
```
That's all for now :-)

**Comment by cslux** [comment] 2015-10-09 12:02
I can look into that in more detail when I have installed Windows and cygwin on my Tower again, but this can take a while.

**Comment by cslux** [comment] 2015-10-09 19:22
Ok, just tried to compile rtags at home once more with clang and it works. This leads to the conclusion that the clang version 3.5.2 in cygwin has no c++11 support, as correctly detected by the rct.cmake test snippet, and hence, clang doesn't support the keyword `thread_local`,where as GCC supports it in cygwin.

**Comment by cslux** [comment] 2015-10-09 19:25
I think you can close issue #215 as the initial problem is solved.

**Comment by Andersbakken** [comment] 2015-10-10 01:28
Ok. I'll close it until told otherwise then :-)

Anders

**Closed** 2018-06-07 12:28 UTC
Labels: bug, enhancement
