### ISSUE TITLE
Emacs byte compilation failed

### ISSUE THREAD

**Issue by chep** [Andersbakken/rtags#1368] opened 2020-01-14 15:49 UTC
I compile myself emacs master branch and update my packages very often

I can't install rtags with my aur package manager (archlinux):
>Symbol’s value as variable is void: ivy-completing-read-handlers-alist

This patch fixed it but I'm not sure if it can be used as-is:
```
From 4aa7307206c7d5c373f59fb5820e7b53bfb4871f Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?C=C3=A9dric=20Ch=C3=A9pied?= <cedric.chepied@delair.aero>
Date: Tue, 14 Jan 2020 16:38:44 +0100
Subject: [PATCH] add ivy-completing-read-handlers-alist

---
 src/compile-shim.elisp | 1 +
 1 file changed, 1 insertion(+)

diff --git a/src/compile-shim.elisp b/src/compile-shim.elisp
index 22509b6e..c8fa3231 100644
--- a/src/compile-shim.elisp
+++ b/src/compile-shim.elisp
@@ -15,6 +15,7 @@
   (defun ivy-state-current (&rest args))
   (defun ivy--get-window (&rest args))
   (defun ivy-state-buffer (&rest args))
+  (defvar ivy-completing-read-handlers-alist nil)
   (defun ivy-recursive-restore (&rest args))
   (defvar ivy-last nil)
   (defvar ivy-exit nil)
-- 
2.24.1
```

**Environment (please complete the following information):**
 - OS/Version: Archlinux
 - RTags(rdm,rc): v2.37
 - Emacs: 28.0.50
 - LLVM/Clang: 8.0.1

**Comment by cslux** [comment] 2020-01-14 18:15
This is how we fixed it in 132ab7ce. 

Duplicate of #1359.

**Closed by cslux** 2020-01-14 18:15 UTC
