### ISSUE TITLE
Unable to load compilation database wit bear version 2.3.4

### ISSUE THREAD

**Issue by schultzern** [Andersbakken/rtags#955] opened 2017-04-25 13:21 UTC
Hi there,

I use bear to generate compile_commands.json via make and I currently use rtags version 2.9.117.

With bear version 2.3.4 I get the following error when trying to upload my compile_commands.json to rdm: 

> LIBCLANG TOOLING ERROR: Json-compilation-database: Expected string as value
   Can't load compilation database from /path/to/compile_commands.json

This might be an issue with bear but I'm reporting since you specify that one can use bear to generate compilation database. When I use bear version 2.2.1 everything works as expected. 

PS: Thanks for making rtags. Great software.

**Comment by cslux** [comment] 2017-04-25 18:06
@schultzern I can't reproduce this with Bear 2.3.4 and 2.9.117. Can you provide an example where Bear produced a faulty compile_commands.json file?

Christian

PS: Thank you :-)

**Comment by schultzern** [comment] 2017-04-26 12:51
Sure! I've attached the compile_commands.json I get from using bear 2.3.4 on the current rtags repo state. Thanks for the help!
[compile_commands.zip](https://github.com/Andersbakken/rtags/files/958387/compile_commands.zip)

**Comment by cslux** [comment] 2017-04-27 12:55
@schultzern I can't reproduce this with your compile_commands.json file either. When I substitute the paths with my paths on my system, the compile_commands.json file loads just fine.  Could be a clang problem:

```
LIBCLANG TOOLING ERROR: Json-compilation-database: Expected string as value
```
Indicates a clang error, and since  clang tooling fails to load the database, RTags prints 
```
Can't load compilation database from /path/to/compile_commands.json
```

However, since I have the exact same version on my system installed this seems strange to me.

I attached my compile_commans.json file as reference.

[compile_commands.zip](https://github.com/Andersbakken/rtags/files/961614/compile_commands.zip)

Did you install LLVM/Clang through your system packages manager?
What OS do you use?

Christian

**Comment by cslux** [comment] 2017-04-27 13:45
It's a Bear "issue". Bear now adds the key "arguments" to the compile_commands.json, where each value is a separated string, instead of the key "command" where the compilation command was a single string. Why is it working for me and not for you? I have no glue :-/.

**Comment by cslux** [comment] 2017-04-27 13:47
If you create the compile_commands.json database with CMake it should work.

``` bash
cd rtags && cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 . 
```

**Comment by schultzern** [comment] 2017-04-28 07:39
Thanks for the help! 

I'm on Cent OS 7.2 and have installed LLVM/Clang though yum:
_clang-3.4.2-8.el7.x86_64_, _clang-devel-3.4.2-8.el7.x86_64_, _llvm3.9-libs-3.9.1-5.el7.x86_64_, _llvm3.9-devel-3.9.1-5.el7.x86_64_, _llvm3.9-libs-3.9.1-5.el7.x86_64_

I can confim that it works with cmake exporting the compile commands. I think I'll stick with the older version of bear for now :)

**Comment by schultzern** [comment] 2017-04-28 07:51
> It's a Bear "issue". Bear now adds the key "arguments" to the compile_commands.json, where each value is a separated string, instead of the key "command" where the compilation command was a single string. Why is it working for me and not for you? I have no glue :-/.

I also noticed this and I assume this is the reason. However it's strange that it works for you and not me... What system are you on? What versions of clang and llvm do you have installed?

Also: When i build rtags from source I use the following cmake command:
_cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DRTAGS_NO_ELISP_FILES=1 -DLIBCLANG_LIBDIR="/usr/lib64/llvm" .._ 

I had to to so to be able to generate makefiles. I suspect that it's something fishy with the last part where I manually specify the path to _libclang.so_, and it's probably a good hint that rtags complains about a libclang tooling error..

**Comment by cslux** [comment] 2017-04-28 07:53
> clang-3.4.2-8.el7.x86_64, clang-devel-3.4.2-8.el7.x86_64, llvm3.9-libs-3.9.1-5.el7.x86_64, llvm3.9-devel-3.9.1-5.el7.x86_64, llvm3.9-libs-3.9.1-5.el7.x86_64

Is there a reason you have clang-3.4.2 installed but on the other hand llvm-3.9? Now I'm 100% sure it's a issue with your installed packages. Any chance you can update `clang` and `clang-devel `and try it again.
The error `LIBCLANG TOOLING ERROR: Json-compilation-database: Expected string as value` comes from `clang-devel`.

I'm on Fedora 25 
- clang-libs-3.9.1-2.fc25.x86_64
- llvm-libs-3.9.1-2.fc25.x86_64
- clang-3.9.1-2.fc25.x86_64
- llvm-devel-3.9.1-2.fc25.x86_64
- llvm-libs-3.9.1-2.fc25.i686
- llvm-3.9.1-2.fc25.x86_64
- clang-devel-3.9.1-2.fc25.x86_64

**Comment by cslux** [comment] 2017-04-28 08:09
@schultzern 

I looked at the clang (cfe) 3.4 source code, and indeed it doesn't contain the code to handle the compile_commands.json key "arguments". You need to update your `clang` and `clang-devel` package.

This is the code which handles the "arguments" key. 
https://github.com/llvm-mirror/clang/blob/5ca7f4286d20192dff833f91865b10be0debd76d/lib/Tooling/JSONCompilationDatabase.cpp#L314 

While you see the error from this version of `JSONCompilationDatabase.cpp`.
https://github.com/llvm-mirror/clang/blob/860df574e7a0a3f1c4fa1a2eb8280c20e7f02027/lib/Tooling/JSONCompilationDatabase.cpp#L265

I'm closing this issue since it's an issue with your installation. If you need any help let me know it.

Christian

**Closed by cslux** 2017-04-28 08:09 UTC

**Comment by schultzern** [comment] 2017-04-28 11:40
Thanks! makes sense... Appriciate the assistance.

The reason is that's whats available for CentOS unfortunately. If not I have to build it from source. Latest rpm package I found was 3.4.2. The company I work for uses CentOS so I'm stuck with the distro for now... However I'll try on my Debian machine at home during the weekend and get back to you.

Cheers,
Eirik

**Comment by helinwang** [comment] 2017-11-30 19:54
Can confirm after installing everything with 3.9 (clang, llvm) works. Note you have to recompile rtags after the update.
It's strange the cmake for rtags needs `libclang-dev`, but `libclang-dev` installs:
```
 libclang-3.4-dev libclang-common-3.4-dev libclang-dev libclang1-3.4
  libllvm3.4
```
again, however even both 3.4 and 3.9 exist, it seems that things were not messed up.
