### ISSUE TITLE
Completions unavailable after "libclang: crash detected in code completion"

### ISSUE THREAD

**Issue by Nephyrin** [Andersbakken/rtags#747] opened 2016-07-06 20:46 UTC
I rarely get `libclang: crash detected in code completion`, however, when it does happen, completions just stop working until I restart rdm.  It would be nice to have the option to just have rdm shutdown, at a minimum, so it can auto-restart and self-heal.

**Comment by Andersbakken** [comment] 2016-07-07 17:28
Hm. I don't entirely see why that should happen. Are you able to reproduce
a crash reliably? I'd like to take a look at that.

Anders

**Comment by Nephyrin** [comment] 2016-07-08 23:32
Unfortunately I'm not, it seems to be on files with lots of errors, possibly when rdm is busy reparsing things.  It happened again today, and I noticed that if I C-g and re-request the completion (synchronous completions mode) it prints the crash message again, so it seems like some internal state just becomes irrevocably corrupt.

I'll keep an eye out for a reliable repro.

**Comment by azuk** [comment] 2016-11-09 14:38
I also have a problem that completions stop working until rdm restart but it doesn't follow a crash. It _seems_ it follows a momentary situation where the code doesn't compile (due to undeclared identifier, for example) but I haven't been able to reproduce it with small example code. Anyway, it could be that the crash and completions stopping working until rdm restart are two separate problems -- at least the latter is for me.

The problem occurs fairly often in my real large code base. I've also faced other problems that I've been unable to reproduce with a small example and I would expect this to happen to others as well. I've been wondering if it was possible to add some self-diagnostics to rtags to help investigate such problems? Back when I used CEDET it had something like that and recall it was helpful.

**Comment by Andersbakken** [comment] 2016-11-20 20:53
I think it might be a mutex situation. If clang crashes it longjmp's away
to "recover".

If mutexes were locked at the time of crash we might never be able to call
those clang APIs again.

If anyone could find a way to reliably reproduce I would love to analyze it
further. This is part of the reason we run the indexing in a separate
process rather than a separate thread. Maybe completions should be done
that way too actually. It's just trickier since we have to persist the
translation unit between completion requests.

Anders

**Comment by Nephyrin** [comment] 2016-11-24 00:39
I see this regularly, but can never reproduce :-/ Restarting rdm and performing the same command generally works.  Anecdotally, it may be related to saving a buffer, editing it, and then requesting completions, in short-order.

As a kind of crappy workaround, an option to have rdm re-exec itself on these failures to force a fresh state might greatly reduce the pain of underlying clang buginess.

**Comment by Andersbakken** [comment] 2016-12-06 15:09
Sorry about the long delay.

That's a good idea actually. I'll look into adding something for that.

Anders

**Comment by sebastiansturm** [comment] 2017-02-27 12:03
I think I found a surefire way to reproduce this. We're currently using a code generator at work to compile data description files into .cpp helper classes; every recompilation generates approximately 500KB of C++ code within a few milliseconds and as far as I can tell, this triggers a libclang crash every time. I'm not allowed to share that code, but I guess I should be able to achieve a similar effect by quickly copying modified source files into the project directory. Maybe I can prepare a reproducible test case next weekend

**Comment by Andersbakken** [comment] 2017-03-11 20:08
That would definitely be interesting. It's not unlikely that there simply
isn't much we can do about it. Maybe we could have a limit to the size of
the source file (assuming this is the crux of issue) and just refuse to
parse it if it's larger than some value.

Anders

**Comment by sebastiansturm** [comment] 2017-03-20 20:35
It seems I'm no longer able to trigger this crash (with a cleanly checked out copy of rtags and the latest versions of libclang-3.9 / libclang-4.0). The size of my autogenerated source files has only increased in the meantime, so the real reason behind these crashes is probably a bit more involved than I had thought. I'll let you know if/when it happens again

**Comment by Nephyrin** [comment] 2017-03-20 20:37
I have also not seen this in a while (month+) after seeing it daily for a while

**Comment by Andersbakken** [comment] 2017-03-21 01:02
Well. It always originated inside of libclang so maybe the bug is fixed on
their side. That would be the best solution.

Anders

**Closed** 2018-06-07 13:21 UTC
