### ISSUE TITLE
Getting completely irrelevant function references

### ISSUE THREAD

**Issue by YorkZ** [Andersbakken/rtags#487] opened 2015-10-27 16:35 UTC
I'm on commit d781c53, with rct commit 5d9aedc. When I run `rtags-find-references-at-point`, most of the time I got the error:

`/usr/bin/rc --current-file=path/to/tr.cpp -r path/to/tr.cpp:161:6: Failed to open ~/.rtags/_home_LOGINNAME_MY_PROJECT_NAME_/0/targets (2) 71.`

Despite getting this error message, some times I still got correct results. But some times I got completely irrelevant references to the function at point. There is a case when there should have been only two references of the function, but I got 1000.

I checked the .rtags directory, there was no sub directory name "0", and the lowest numbered sub directory was "10".

I've also tried deleting the entire .rtags directory and then rebuilding the index. But that didn't make any difference!

Thanks,

York

**Comment by YorkZ** [comment] 2015-10-29 14:53
Any idea?

**Comment by Andersbakken** [comment] 2015-10-30 05:10
Hi York

Hm. I don't entirely see how this would happen (not doubting that it does).
Are you able to reliably reproduce this at all? I'd love to fix it but I
don't entirely know where to begin.

Anders

**Comment by YorkZ** [comment] 2015-10-30 13:04
This is happening here all the time. Almost every time I run `rtags-find-references-at-point` I got the error message:

`/usr/bin/rc --current-file=path/to/tr.cpp -r path/to/tr.cpp:161:6: Failed to open ~/.rtags/_home_LOGINNAME_MY_PROJECT_NAME_/0/targets`

I sometimes get this message when running `rtags-find-symbol-at-point`.

**Comment by Andersbakken** [comment] 2015-12-31 07:36
Hi York

Are you still seeing this problem?

**Comment by YorkZ** [comment] 2016-01-02 15:23
Hi Andersbakken,

I'm still using the git commit I mentioned in this issue report. And yes, it is still a problem I've been suffering single everyday. Have you done anything about it? If so, do you think I should try the latest version?

Thanks,

York

**Comment by Andersbakken** [comment] 2016-01-02 19:42
I was never able to reproduce it so I can't say for sure if it has been
fixed but in general I'd recommend always staying on the latest version. It
might very well have been fixed.

Anders

**Comment by YorkZ** [comment] 2017-02-11 18:46
Hi Andersbakken,

I guess this problem is related to Qt's moc compiler. I guess when I make changes in a Qt mocable header file, as soon as I save it, rtags starts re-indexing. However, this re-indexing is premature because the updated header hasn't been compiled by Qt moc yet, and therefore the moc_*.cpp hasn't been generated yet.

If you need, I could provide a minimum Qt source that you can use to reproduce the issue.

**Comment by Andersbakken** [comment] 2017-02-13 16:33
Hi York

I actually worked at Trolltech for 10 years or so so I'm quite familiar
with moc :-)

I understand the problem but I am not entirely sure how it should be fixed.
It seems relatively hacky to make RTags not reindex the moc_ files when the
header is modified. Not least of which because for many types of changes we
would want it reindexed.

Do you have an idea for how you'd like this to work?

regards

Anders

**Closed** 2018-06-07 12:40 UTC
