### ISSUE TITLE
rdm very unstable

### ISSUE THREAD

**Issue by YorkZ** [Andersbakken/rtags#1278] opened 2019-01-14 20:09 UTC
**Describe the bug**
`rdm` seems to be extremely unstable. The process either frequently restarts itself, or dies without being able to restart.
**To Reproduce**
1. At shell prompt on host A, run:
```bash
    rdm
```
2. From host B, `ssh` into host A
3. 90% of the times, the `rdm` process on host A would be killed.
4. On host B, logout host A
5. Probably 70% of times `rdm` on host A would be killed.

**Environment (please complete the following information):**
 - Ubuntu 14.04 Vagrant VM
 - RTags(rdm,rc): [2.21.126]
 - Emacs: [26.1]
 - LLVM/Clang: [7.0]

**Comment by zhihuiFan** [comment] 2019-01-15 04:30
this looks very strange to me since I did the similar thing (run rdm on a vm and login/loutout to use rdm) and it worked well.    and I have used it for more than half years and it work pretty well ( now I run rdm locally)

is it possible that you vm is lack of resource, like memory?  and rdm is killed by oom (you can tell this by run `dmesg | grep -i oom`)

**Comment by YorkZ** [comment] 2019-01-15 06:35
@zhihuiFan Are you using the latest `rtags`? Is it possible for you to try commit 6e019c7b?

I've been using `rtags` for many years and rarely have much problem. Before updating to 6e019c7b, I've been using version 2.18.125, commit 1779d7e8 for a few months. It wasn't until yesterday that I noticed 1779d7e8 has similar problems, but it at least works. Whereas 6e019c7b is extremely unstable and is almost unusable.

> is it possible that you vm is lack of resource, like memory? and rdm is killed by oom

I'm pretty sure this is not the problem because I have two VMs, one of them has 1G bytes memory and the other, 4 G bytes. Again, 1779d7e8 worked for me for months.

**Comment by YorkZ** [comment] 2019-01-19 15:10
Nobody?

**Comment by cslux** [comment] 2019-01-19 15:55
@YorkZ I'm afraid, but I can't reproduce it.

**Comment by cslux** [comment] 2019-01-19 16:35
No VM! But I will setup one or two up, to try it out.

**Comment by cslux** [comment] 2019-01-19 16:36
To you have to images by hand?

**Comment by cslux** [comment] 2019-01-19 16:40
@YorkZ a tutorial or something like that to mirror your setup would be nice

**Comment by tillt** [comment] 2019-01-21 13:35
> Probably 70% of times rdm on host A would be killed.

This sounds rather weird and without additional logging added to the report, impossible to debug.

**Comment by Andersbakken** [comment] 2019-08-21 04:14
Please reopen if this still is an issue. I would also recommend running rdm in gdb to see why it dies if this stiill happens. Closing for now due to the age of the bug,

**Closed by Andersbakken** 2019-08-21 04:14 UTC

**Comment by YorkZ** [comment] 2019-08-22 04:01
I don't know whether this is still happening or not, I just don't use `rdm` in a VM anymore because of this deal breaker issue.  However, if you've never tried to address it, it's highly unlikely the issue would go away by itself. For this reason, I doubt whether closing the issue would be appropriate.
